### ISSUE TITLE
Sample playback on note off event when max velocity fixed is used

### ISSUE THREAD

**Issue by richb93** [rafaelpernil2/PolyVolcaWeb#1]
Hi!

Firstly, thanks for a great little tool! I stumbled across this after seeing you post on reddit - super fun and useful to boot!

Anyhow, just wanted to submit an issue regarding sample playback on note off events when max velocity fixed is used. I can press a key and when I lift off, the note off event is also being played, producing an odd (if not slightly cool) effect.

**Comment by rafaelpernil2** [comment]
Hi @richb93 

I have just tested that scenario and I cannot replicate the issue. See: 
![image](https://github.com/rafaelpernil2/PolyVolcaWeb/assets/9103141/4d354fde-c075-400e-9b57-80c0e3c10465)


"2-UM-ONE" is my keyboard
"loopMIDI Port" represents the volca sample2. I use a loopback MIDI port to show as output what the volca would receive as input

I have tried the following:

1. Open the web app
2. Configure "2-UM-ONE" as input with channel 1
3. Configure "loopMIDI Port" as output 
4. Set sample to 120 (from default sample set provided by KORG)
5. Set "Key velocity" to "Max. velocity fixed"
6. Press middle C on my keyboard (note on)
7. Release middle C key on my keyboard (note off)

![image](https://github.com/rafaelpernil2/PolyVolcaWeb/assets/9103141/df86baae-7780-46ac-8249-6cf81863a68b)


Result:

1. Keyboard note on is registered
2. volca sample2 receives these Control Change values:  
    - CC#49 - 64 (pitch)
    - CC#7 - 127 (velocity/volume)
    - CC#10 - 60 (pan)
4. volca sample2 receives note on
5. Keyboard note off is registered
6. volca sample2 receives this Control Change value:
    - CC#7 - 0 (velocity/volume)

That means, there is no note being re-sent when a note-off is detected. It just changes the track volume to 0

**Comment by rafaelpernil2** [comment]
Maybe your issue is caused by your MIDI keyboard. If you can, try to use a different one or check the settings of your device
